name: MarkdownEditor
options:
  bundleIdPrefix: com.zerolive
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

targets:
  MarkdownEditor:
    type: application
    platform: macOS
    sources:
      - MarkdownEditor
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.zerolive.MarkdownEditor
        PRODUCT_NAME: MarkdownEditor
        MARKETING_VERSION: "1.0.1"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_FILE: MarkdownEditor/Info.plist
        CODE_SIGN_STYLE: Manual
        DEVELOPMENT_TEAM: XU8HS9JUTS
        CODE_SIGN_IDENTITY: "Developer ID Application"
        ENABLE_HARDENED_RUNTIME: YES
        COMBINE_HIDPI_IMAGES: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "13.0"
    info:
      path: MarkdownEditor/Info.plist
      properties:
        CFBundleName: MarkdownEditor
        CFBundleDisplayName: Markdown Editor
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundlePackageType: APPL
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIconFile: ""
        CFBundleIconName: AppIcon
        LSMinimumSystemVersion: $(MACOSX_DEPLOYMENT_TARGET)
        NSMainStoryboardFile: ""
        NSPrincipalClass: NSApplication
        NSHighResolutionCapable: true
        CFBundleDocumentTypes:
          - CFBundleTypeName: Markdown Document
            CFBundleTypeRole: Editor
            LSHandlerRank: Owner
            LSItemContentTypes:
              - net.daringfireball.markdown
              - public.plain-text
            CFBundleTypeExtensions:
              - md
              - markdown
        UTExportedTypeDeclarations:
          - UTTypeIdentifier: net.daringfireball.markdown
            UTTypeDescription: Markdown Document
            UTTypeConformsTo:
              - public.plain-text
            UTTypeTagSpecification:
              public.filename-extension:
                - md
                - markdown
        NSSupportsAutomaticTermination: true
        NSSupportsSuddenTermination: false

  MarkdownEditorTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - MarkdownEditorTests
    dependencies:
      - target: MarkdownEditor
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.zerolive.MarkdownEditorTests

schemes:
  MarkdownEditor:
    build:
      targets:
        MarkdownEditor: all
        MarkdownEditorTests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - MarkdownEditorTests
    archive:
      config: Release
